 
  
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: BuildTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  GLOBAL_VAR: "Global"
  TEST_FOLDER: "tests"
  TEST_PROJECT: "TestProject1"
  WIKI_MOVER_ROOT: "/github/workspace"
  COVERAGE_FOLDER: "CoverageReport"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v3


    - name: Dump github context
      run:   echo "$GITHUB_CONTEXT"
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}


    - name: Set Variables
      run: |
        # Test Folder
        echo "TEST_PATH=$GITHUB_WORKSPACE/$TEST_FOLDER"
        source $GITHUB_ENV

        # Test Project Folder
        echo "TEST_PROJECT_PATH=$TEST_PATH/$TEST_PROJECT" >> $GITHUB_ENV
        
        # Test Code Coverage Report
        echo "TEST_COVERAGE_REPORT=$TEST_PATH/$COVERAGE_FOLDER" >> $GITHUB_ENV

        #source $GITHUB_ENV
        echo "Repo Name=${{ github.event.repository.name }}"
        echo "WIKI_MOVER_ROOT = $WIKI_MOVER_ROOT"

        # WIKI Mover Coverage Report Src Location.  Same as Test Code Coverage Report - but different starting point as running in a docker container.
        echo "WIKI_COVERAGE_PATH=$WIKI_MOVER_ROOT/$TEST_FOLDER/$COVERAGE_FOLDER/" >> $GITHUB_ENV
        
        echo "/github/workspace/src/Test_StreamProcessorLibrary/report/"


    - name: Display Variables
      run: |
        echo "Global Var:            $GLOBAL_VAR"
        echo "Github_env:            $GITHUB_ENV"
        echo "GitHome Workspace:     $GITHUB_WORKSPACE"
        echo "Test_Path:             $TEST_PATH"
        echo "Test_Project_Path:     $TEST_PROJECT_PATH"
        echo "Test_Coverage_Report:  $TEST_COVERAGE_REPORT"
        echo "Wiki Mover Root:       $WIKI_MOVER_ROOT"
        echo "WIKI Coverage Path     $WIKI_COVERAGE_PATH"


    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x


# From https://github.com/im-open/code-coverage-report-generator
