 
  
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: BuildTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  GLOBAL_VAR: "Global"
  

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
    - uses: actions/checkout@v3


    - name: Set Variables
      run: |
        echo "SOMEDIR=$GITHUB_WORKSPACE/somedir" >> $GITHUB_ENV
        source $GITHUB_ENV
        echo "SUBDIR=$SOMEDIR/subfolder" >> $GITHUB_ENV

    - name: Display Variables
      run: |
        echo "Global Var: $GLOBAL_VAR"
        echo "Github_env: $GITHUB_ENV"
        echo "GitHome Workspace:  $GITHUB_WORKSPACE"
        echo "SomeDir:   $SOMEDIR"
        echo "SubDir:    $SUBDIR"

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x


# From https://github.com/im-open/code-coverage-report-generator
